### ISSUE TITLE
последний релиз пустой

### ISSUE THREAD

**Issue by BK8000L** [savely-krasovsky/antizapret-sing-box#10]
в списке ничего нет

**Comment by savely-krasovsky** [comment]
спасибо, откатил, посмотрю в чём дело

**Comment by savely-krasovsky** [comment]
@BK8000L починил, авторы антизапрет изменили формат дампа с чистого csv на gziped csv, добавил дополнительный декодер, обновил заливалку, всё работает. Спасибо за репорт, закрываю.
