### ISSUE TITLE
Не рабочий конфиг

### ISSUE THREAD

**Issue by MetalistPavlenko** [savely-krasovsky/antizapret-sing-box#4]
Ошибка:

sing-box run -c wg0.json
←[31mERROR←[0m[0000] outbound/wireguard[wireguard-out]: failed to read packet from tun device: invalid argument
←[31mERROR←[0m[0003] dns: lookup failed for github.com: exchange6: Post "https://dns.adguard-dns.com/dns-query": dial tcp 94.140.15.15:443: connectex: An established connection was aborted by the software in your host machine. | dial tcp 94.140.14.14:443: An invalid argument was supplied. | exchange4: Post "https://dns.adguard-dns.com/dns-query": dial tcp 94.140.15.15:443: connectex: An established connection was aborted by the software in your host machine. | dial tcp 94.140.14.14:443: An invalid argument was supplied.
←[31mFATAL←[0m[0003] start service: initialize rule-set[0]: initial rule-set: antizapret: Get "https://github.com/savely-krasovsky/antizapret-sing-box/releases/latest/download/antizapret.srs": exchange6: Post "https://dns.adguard-dns.com/dns-query": dial tcp 94.140.15.15:443: connectex: An established connection was aborted by the software in your host machine. | dial tcp 94.140.14.14:443: An invalid argument was supplied. | exchange4: Post "https://dns.adguard-dns.com/dns-query": dial tcp 94.140.15.15:443: connectex: An established connection was aborted by the software in your host machine. | dial tcp 94.140.14.14:443: An invalid argument was supplied.

Конфиг:
{
    "log": {
      "level": "warn"
    },
    "dns": {
      "servers": [
        {
          "tag": "adguard-dns",
          "address": "https://dns.adguard-dns.com/dns-query",
          "address_resolver": "local-dns",
          "detour": "wireguard-out"
        },
        {
          "tag": "local-dns",
          "address": "local",
          "detour": "direct-out"
        }
      ],
      "rules": [
        {
          "outbound": "any",
          "server": "local-dns"
        }
      ]
    },
    "inbounds": [
      {
        "type": "tun",
        "inet4_address": "172.16.8.1/30",
        "auto_route": true,
        "strict_route": true,
        "sniff": true
      }
    ],
    "outbounds": [
      {
        "type": "direct",
        "tag": "direct-out"
      },
      {
        "type": "wireguard",
        "tag": "wireguard-out",
        "server": "162.159.192.5",
        "server_port": 2408,
        "system_interface": true,
        "local_address": [
          "172.16.0.2/32",
          "2606:4700:110:843f:dc80:6f45:9df7:c43d/128"
        ],
        "private_key": "4GpS7uCwST7RnnBfxNLpJCrPByonxGd+z8YLscSLk2w=",
        "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
      },
      {
        "type": "dns",
        "tag": "dns-out"
      }
    ],
    "route": {
      "rules": [
        {
          "rule_set": "antizapret",
          "outbound": "wireguard-out"
        },
        {
          "protocol": "dns",
          "outbound": "dns-out"
        }
      ],
      "rule_set": [
        {
          "tag": "antizapret",
          "type": "remote",
          "format": "binary",
          "url": "https://github.com/savely-krasovsky/antizapret-sing-box/releases/latest/download/antizapret.srs",
          "download_detour": "wireguard-out"
        }
      ],
      "auto_detect_interface": true
    },
    "experimental": {
      "cache_file": {
        "enabled": true
      }
    }
}

**Comment by savely-krasovsky** [comment]
Посмотрите конфиг тут: https://krasovs.ky/2024/08/05/sing-box-bypass.html
Я внес правки, если есть какие-то проблемы, оставляйте комменатрии там. Если всё ок, перенесу пример в этот реп.
